spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/im_system #url
    username: root  #用户名
    password:   #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动

  elasticsearch:
    rest:
      uris: http://localhost:9200
      username:
      password:

jwt:
  secret: Only4IM-System
  ttl: 600000

logging:
  level:
    root=INFO: